spring:
  profiles:
    active: dev

  application:
    name: bazaar-analyze

# Ob-havo API
weather:
  api:
    key: 522c2096ae616aecea1e0f75e299ab2f

# world population API
world:
  population:
    key: 81a792cd66mshcc882743df9f3c9p155a1ejsn45a2d38dde05


# global trading API
api:
  exchangerates:
    key: e373921f7f6a5201e66a0522

# Daily news
daily:
  news:
    key: 3f02205a35ae4c64988a77c5876904bd

# crypto API key
crypto:
    api:
      key: a345ee8c-af1b-4198-a1bf-9af6fc0460b1

# Combinant API key
combinant:
  api:
    key: c9bff330a58fc12cbf7932527578e486

# Jahon banki


