server:
  port: ${PORT:1972}

spring:

#  NoQSL
#  data:
#    mongodb:
#      host: 27017
#      database: mongotoken
#      username: tokenmongo
#      password: tokenmongo

# SQL
  datasource:
    url: jdbc:postgresql://cc0gj7hsrh0ht8.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com/d8qk4kskekgsiu
    username: u8baa4s0082rud
    password: pb268781a577bbe651841507986d6e9aa31038bd0489efc82bab0c5e6a50b0043
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: MyHikariCP

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true

#  thmeleaf bila ishlash qismi
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

# Security
  security:
    user:
      name: login
      password: parol

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# Swagger bilan ishlash qismi
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
